name: MinecraftPlugin
version: ${project.version}
main: minecraftplugin.minecraftplugin.MinecraftPlugin
authors: [derteufelqwe]
description: Essentials for DockerMC

depend:
    - Vault

commands:
    dockermc:
        description: Utility commands for DockerMC
        aliases: [dmc]
    teleportsign:
        description: Create a teleport sign to teleport to other servers
        aliases: [tpsign]
