// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entry.proto
package de.derteufelqwe.driver.protobuf;


public final class Entry {
  private Entry() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LogEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LogEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string source = 1;</code>
     * @return The source.
     */
    java.lang.String getSource();
    /**
     * <code>string source = 1;</code>
     * @return The bytes for source.
     */
    com.google.protobuf.ByteString
        getSourceBytes();

    /**
     * <code>int64 time_nano = 2;</code>
     * @return The timeNano.
     */
    long getTimeNano();

    /**
     * <code>bytes line = 3;</code>
     * @return The line.
     */
    com.google.protobuf.ByteString getLine();

    /**
     * <code>bool partial = 4;</code>
     * @return The partial.
     */
    boolean getPartial();

    /**
     * <code>.PartialLogEntryMetadata partial_log_metadata = 5;</code>
     * @return Whether the partialLogMetadata field is set.
     */
    boolean hasPartialLogMetadata();
    /**
     * <code>.PartialLogEntryMetadata partial_log_metadata = 5;</code>
     * @return The partialLogMetadata.
     */
    Entry.PartialLogEntryMetadata getPartialLogMetadata();
    /**
     * <code>.PartialLogEntryMetadata partial_log_metadata = 5;</code>
     */
    Entry.PartialLogEntryMetadataOrBuilder getPartialLogMetadataOrBuilder();
  }
  /**
   * Protobuf type {@code LogEntry}
   */
  public static final class LogEntry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LogEntry)
      LogEntryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LogEntry.newBuilder() to construct.
    private LogEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogEntry() {
      source_ = "";
      line_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LogEntry();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LogEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              source_ = s;
              break;
            }
            case 16: {

              timeNano_ = input.readInt64();
              break;
            }
            case 26: {

              line_ = input.readBytes();
              break;
            }
            case 32: {

              partial_ = input.readBool();
              break;
            }
            case 42: {
              Entry.PartialLogEntryMetadata.Builder subBuilder = null;
              if (partialLogMetadata_ != null) {
                subBuilder = partialLogMetadata_.toBuilder();
              }
              partialLogMetadata_ = input.readMessage(Entry.PartialLogEntryMetadata.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(partialLogMetadata_);
                partialLogMetadata_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Entry.internal_static_LogEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Entry.internal_static_LogEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Entry.LogEntry.class, Entry.LogEntry.Builder.class);
    }

    public static final int SOURCE_FIELD_NUMBER = 1;
    private volatile java.lang.Object source_;
    /**
     * <code>string source = 1;</code>
     * @return The source.
     */
    @java.lang.Override
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        source_ = s;
        return s;
      }
    }
    /**
     * <code>string source = 1;</code>
     * @return The bytes for source.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_NANO_FIELD_NUMBER = 2;
    private long timeNano_;
    /**
     * <code>int64 time_nano = 2;</code>
     * @return The timeNano.
     */
    @java.lang.Override
    public long getTimeNano() {
      return timeNano_;
    }

    public static final int LINE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString line_;
    /**
     * <code>bytes line = 3;</code>
     * @return The line.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getLine() {
      return line_;
    }

    public static final int PARTIAL_FIELD_NUMBER = 4;
    private boolean partial_;
    /**
     * <code>bool partial = 4;</code>
     * @return The partial.
     */
    @java.lang.Override
    public boolean getPartial() {
      return partial_;
    }

    public static final int PARTIAL_LOG_METADATA_FIELD_NUMBER = 5;
    private Entry.PartialLogEntryMetadata partialLogMetadata_;
    /**
     * <code>.PartialLogEntryMetadata partial_log_metadata = 5;</code>
     * @return Whether the partialLogMetadata field is set.
     */
    @java.lang.Override
    public boolean hasPartialLogMetadata() {
      return partialLogMetadata_ != null;
    }
    /**
     * <code>.PartialLogEntryMetadata partial_log_metadata = 5;</code>
     * @return The partialLogMetadata.
     */
    @java.lang.Override
    public Entry.PartialLogEntryMetadata getPartialLogMetadata() {
      return partialLogMetadata_ == null ? Entry.PartialLogEntryMetadata.getDefaultInstance() : partialLogMetadata_;
    }
    /**
     * <code>.PartialLogEntryMetadata partial_log_metadata = 5;</code>
     */
    @java.lang.Override
    public Entry.PartialLogEntryMetadataOrBuilder getPartialLogMetadataOrBuilder() {
      return getPartialLogMetadata();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSourceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, source_);
      }
      if (timeNano_ != 0L) {
        output.writeInt64(2, timeNano_);
      }
      if (!line_.isEmpty()) {
        output.writeBytes(3, line_);
      }
      if (partial_ != false) {
        output.writeBool(4, partial_);
      }
      if (partialLogMetadata_ != null) {
        output.writeMessage(5, getPartialLogMetadata());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSourceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, source_);
      }
      if (timeNano_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timeNano_);
      }
      if (!line_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, line_);
      }
      if (partial_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, partial_);
      }
      if (partialLogMetadata_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getPartialLogMetadata());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Entry.LogEntry)) {
        return super.equals(obj);
      }
      Entry.LogEntry other = (Entry.LogEntry) obj;

      if (!getSource()
          .equals(other.getSource())) return false;
      if (getTimeNano()
          != other.getTimeNano()) return false;
      if (!getLine()
          .equals(other.getLine())) return false;
      if (getPartial()
          != other.getPartial()) return false;
      if (hasPartialLogMetadata() != other.hasPartialLogMetadata()) return false;
      if (hasPartialLogMetadata()) {
        if (!getPartialLogMetadata()
            .equals(other.getPartialLogMetadata())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getSource().hashCode();
      hash = (37 * hash) + TIME_NANO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimeNano());
      hash = (37 * hash) + LINE_FIELD_NUMBER;
      hash = (53 * hash) + getLine().hashCode();
      hash = (37 * hash) + PARTIAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPartial());
      if (hasPartialLogMetadata()) {
        hash = (37 * hash) + PARTIAL_LOG_METADATA_FIELD_NUMBER;
        hash = (53 * hash) + getPartialLogMetadata().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Entry.LogEntry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Entry.LogEntry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Entry.LogEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Entry.LogEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Entry.LogEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Entry.LogEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Entry.LogEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Entry.LogEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Entry.LogEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Entry.LogEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Entry.LogEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Entry.LogEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Entry.LogEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LogEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LogEntry)
        Entry.LogEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Entry.internal_static_LogEntry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Entry.internal_static_LogEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Entry.LogEntry.class, Entry.LogEntry.Builder.class);
      }

      // Construct using Entry.LogEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        source_ = "";

        timeNano_ = 0L;

        line_ = com.google.protobuf.ByteString.EMPTY;

        partial_ = false;

        if (partialLogMetadataBuilder_ == null) {
          partialLogMetadata_ = null;
        } else {
          partialLogMetadata_ = null;
          partialLogMetadataBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Entry.internal_static_LogEntry_descriptor;
      }

      @java.lang.Override
      public Entry.LogEntry getDefaultInstanceForType() {
        return Entry.LogEntry.getDefaultInstance();
      }

      @java.lang.Override
      public Entry.LogEntry build() {
        Entry.LogEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Entry.LogEntry buildPartial() {
        Entry.LogEntry result = new Entry.LogEntry(this);
        result.source_ = source_;
        result.timeNano_ = timeNano_;
        result.line_ = line_;
        result.partial_ = partial_;
        if (partialLogMetadataBuilder_ == null) {
          result.partialLogMetadata_ = partialLogMetadata_;
        } else {
          result.partialLogMetadata_ = partialLogMetadataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Entry.LogEntry) {
          return mergeFrom((Entry.LogEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Entry.LogEntry other) {
        if (other == Entry.LogEntry.getDefaultInstance()) return this;
        if (!other.getSource().isEmpty()) {
          source_ = other.source_;
          onChanged();
        }
        if (other.getTimeNano() != 0L) {
          setTimeNano(other.getTimeNano());
        }
        if (other.getLine() != com.google.protobuf.ByteString.EMPTY) {
          setLine(other.getLine());
        }
        if (other.getPartial() != false) {
          setPartial(other.getPartial());
        }
        if (other.hasPartialLogMetadata()) {
          mergePartialLogMetadata(other.getPartialLogMetadata());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Entry.LogEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Entry.LogEntry) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object source_ = "";
      /**
       * <code>string source = 1;</code>
       * @return The source.
       */
      public java.lang.String getSource() {
        java.lang.Object ref = source_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          source_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string source = 1;</code>
       * @return The bytes for source.
       */
      public com.google.protobuf.ByteString
          getSourceBytes() {
        java.lang.Object ref = source_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          source_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string source = 1;</code>
       * @param value The source to set.
       * @return This builder for chaining.
       */
      public Builder setSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string source = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSource() {
        
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }
      /**
       * <code>string source = 1;</code>
       * @param value The bytes for source to set.
       * @return This builder for chaining.
       */
      public Builder setSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        source_ = value;
        onChanged();
        return this;
      }

      private long timeNano_ ;
      /**
       * <code>int64 time_nano = 2;</code>
       * @return The timeNano.
       */
      @java.lang.Override
      public long getTimeNano() {
        return timeNano_;
      }
      /**
       * <code>int64 time_nano = 2;</code>
       * @param value The timeNano to set.
       * @return This builder for chaining.
       */
      public Builder setTimeNano(long value) {
        
        timeNano_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 time_nano = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeNano() {
        
        timeNano_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString line_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes line = 3;</code>
       * @return The line.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getLine() {
        return line_;
      }
      /**
       * <code>bytes line = 3;</code>
       * @param value The line to set.
       * @return This builder for chaining.
       */
      public Builder setLine(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        line_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes line = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLine() {
        
        line_ = getDefaultInstance().getLine();
        onChanged();
        return this;
      }

      private boolean partial_ ;
      /**
       * <code>bool partial = 4;</code>
       * @return The partial.
       */
      @java.lang.Override
      public boolean getPartial() {
        return partial_;
      }
      /**
       * <code>bool partial = 4;</code>
       * @param value The partial to set.
       * @return This builder for chaining.
       */
      public Builder setPartial(boolean value) {
        
        partial_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool partial = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPartial() {
        
        partial_ = false;
        onChanged();
        return this;
      }

      private Entry.PartialLogEntryMetadata partialLogMetadata_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Entry.PartialLogEntryMetadata, Entry.PartialLogEntryMetadata.Builder, Entry.PartialLogEntryMetadataOrBuilder> partialLogMetadataBuilder_;
      /**
       * <code>.PartialLogEntryMetadata partial_log_metadata = 5;</code>
       * @return Whether the partialLogMetadata field is set.
       */
      public boolean hasPartialLogMetadata() {
        return partialLogMetadataBuilder_ != null || partialLogMetadata_ != null;
      }
      /**
       * <code>.PartialLogEntryMetadata partial_log_metadata = 5;</code>
       * @return The partialLogMetadata.
       */
      public Entry.PartialLogEntryMetadata getPartialLogMetadata() {
        if (partialLogMetadataBuilder_ == null) {
          return partialLogMetadata_ == null ? Entry.PartialLogEntryMetadata.getDefaultInstance() : partialLogMetadata_;
        } else {
          return partialLogMetadataBuilder_.getMessage();
        }
      }
      /**
       * <code>.PartialLogEntryMetadata partial_log_metadata = 5;</code>
       */
      public Builder setPartialLogMetadata(Entry.PartialLogEntryMetadata value) {
        if (partialLogMetadataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          partialLogMetadata_ = value;
          onChanged();
        } else {
          partialLogMetadataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.PartialLogEntryMetadata partial_log_metadata = 5;</code>
       */
      public Builder setPartialLogMetadata(
          Entry.PartialLogEntryMetadata.Builder builderForValue) {
        if (partialLogMetadataBuilder_ == null) {
          partialLogMetadata_ = builderForValue.build();
          onChanged();
        } else {
          partialLogMetadataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.PartialLogEntryMetadata partial_log_metadata = 5;</code>
       */
      public Builder mergePartialLogMetadata(Entry.PartialLogEntryMetadata value) {
        if (partialLogMetadataBuilder_ == null) {
          if (partialLogMetadata_ != null) {
            partialLogMetadata_ =
              Entry.PartialLogEntryMetadata.newBuilder(partialLogMetadata_).mergeFrom(value).buildPartial();
          } else {
            partialLogMetadata_ = value;
          }
          onChanged();
        } else {
          partialLogMetadataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.PartialLogEntryMetadata partial_log_metadata = 5;</code>
       */
      public Builder clearPartialLogMetadata() {
        if (partialLogMetadataBuilder_ == null) {
          partialLogMetadata_ = null;
          onChanged();
        } else {
          partialLogMetadata_ = null;
          partialLogMetadataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.PartialLogEntryMetadata partial_log_metadata = 5;</code>
       */
      public Entry.PartialLogEntryMetadata.Builder getPartialLogMetadataBuilder() {
        
        onChanged();
        return getPartialLogMetadataFieldBuilder().getBuilder();
      }
      /**
       * <code>.PartialLogEntryMetadata partial_log_metadata = 5;</code>
       */
      public Entry.PartialLogEntryMetadataOrBuilder getPartialLogMetadataOrBuilder() {
        if (partialLogMetadataBuilder_ != null) {
          return partialLogMetadataBuilder_.getMessageOrBuilder();
        } else {
          return partialLogMetadata_ == null ?
              Entry.PartialLogEntryMetadata.getDefaultInstance() : partialLogMetadata_;
        }
      }
      /**
       * <code>.PartialLogEntryMetadata partial_log_metadata = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Entry.PartialLogEntryMetadata, Entry.PartialLogEntryMetadata.Builder, Entry.PartialLogEntryMetadataOrBuilder> 
          getPartialLogMetadataFieldBuilder() {
        if (partialLogMetadataBuilder_ == null) {
          partialLogMetadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Entry.PartialLogEntryMetadata, Entry.PartialLogEntryMetadata.Builder, Entry.PartialLogEntryMetadataOrBuilder>(
                  getPartialLogMetadata(),
                  getParentForChildren(),
                  isClean());
          partialLogMetadata_ = null;
        }
        return partialLogMetadataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LogEntry)
    }

    // @@protoc_insertion_point(class_scope:LogEntry)
    private static final Entry.LogEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Entry.LogEntry();
    }

    public static Entry.LogEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogEntry>
        PARSER = new com.google.protobuf.AbstractParser<LogEntry>() {
      @java.lang.Override
      public LogEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogEntry(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LogEntry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogEntry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Entry.LogEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PartialLogEntryMetadataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PartialLogEntryMetadata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool last = 1;</code>
     * @return The last.
     */
    boolean getLast();

    /**
     * <code>string id = 2;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 2;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>int32 ordinal = 3;</code>
     * @return The ordinal.
     */
    int getOrdinal();
  }
  /**
   * Protobuf type {@code PartialLogEntryMetadata}
   */
  public static final class PartialLogEntryMetadata extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PartialLogEntryMetadata)
      PartialLogEntryMetadataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PartialLogEntryMetadata.newBuilder() to construct.
    private PartialLogEntryMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PartialLogEntryMetadata() {
      id_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PartialLogEntryMetadata();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PartialLogEntryMetadata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              last_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 24: {

              ordinal_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Entry.internal_static_PartialLogEntryMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Entry.internal_static_PartialLogEntryMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Entry.PartialLogEntryMetadata.class, Entry.PartialLogEntryMetadata.Builder.class);
    }

    public static final int LAST_FIELD_NUMBER = 1;
    private boolean last_;
    /**
     * <code>bool last = 1;</code>
     * @return The last.
     */
    @java.lang.Override
    public boolean getLast() {
      return last_;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 2;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 2;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDINAL_FIELD_NUMBER = 3;
    private int ordinal_;
    /**
     * <code>int32 ordinal = 3;</code>
     * @return The ordinal.
     */
    @java.lang.Override
    public int getOrdinal() {
      return ordinal_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (last_ != false) {
        output.writeBool(1, last_);
      }
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
      }
      if (ordinal_ != 0) {
        output.writeInt32(3, ordinal_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (last_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, last_);
      }
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
      }
      if (ordinal_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, ordinal_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Entry.PartialLogEntryMetadata)) {
        return super.equals(obj);
      }
      Entry.PartialLogEntryMetadata other = (Entry.PartialLogEntryMetadata) obj;

      if (getLast()
          != other.getLast()) return false;
      if (!getId()
          .equals(other.getId())) return false;
      if (getOrdinal()
          != other.getOrdinal()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LAST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getLast());
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + ORDINAL_FIELD_NUMBER;
      hash = (53 * hash) + getOrdinal();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Entry.PartialLogEntryMetadata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Entry.PartialLogEntryMetadata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Entry.PartialLogEntryMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Entry.PartialLogEntryMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Entry.PartialLogEntryMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Entry.PartialLogEntryMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Entry.PartialLogEntryMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Entry.PartialLogEntryMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Entry.PartialLogEntryMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Entry.PartialLogEntryMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Entry.PartialLogEntryMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Entry.PartialLogEntryMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Entry.PartialLogEntryMetadata prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PartialLogEntryMetadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PartialLogEntryMetadata)
        Entry.PartialLogEntryMetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Entry.internal_static_PartialLogEntryMetadata_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Entry.internal_static_PartialLogEntryMetadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Entry.PartialLogEntryMetadata.class, Entry.PartialLogEntryMetadata.Builder.class);
      }

      // Construct using Entry.PartialLogEntryMetadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        last_ = false;

        id_ = "";

        ordinal_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Entry.internal_static_PartialLogEntryMetadata_descriptor;
      }

      @java.lang.Override
      public Entry.PartialLogEntryMetadata getDefaultInstanceForType() {
        return Entry.PartialLogEntryMetadata.getDefaultInstance();
      }

      @java.lang.Override
      public Entry.PartialLogEntryMetadata build() {
        Entry.PartialLogEntryMetadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Entry.PartialLogEntryMetadata buildPartial() {
        Entry.PartialLogEntryMetadata result = new Entry.PartialLogEntryMetadata(this);
        result.last_ = last_;
        result.id_ = id_;
        result.ordinal_ = ordinal_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Entry.PartialLogEntryMetadata) {
          return mergeFrom((Entry.PartialLogEntryMetadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Entry.PartialLogEntryMetadata other) {
        if (other == Entry.PartialLogEntryMetadata.getDefaultInstance()) return this;
        if (other.getLast() != false) {
          setLast(other.getLast());
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getOrdinal() != 0) {
          setOrdinal(other.getOrdinal());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Entry.PartialLogEntryMetadata parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Entry.PartialLogEntryMetadata) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean last_ ;
      /**
       * <code>bool last = 1;</code>
       * @return The last.
       */
      @java.lang.Override
      public boolean getLast() {
        return last_;
      }
      /**
       * <code>bool last = 1;</code>
       * @param value The last to set.
       * @return This builder for chaining.
       */
      public Builder setLast(boolean value) {
        
        last_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool last = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLast() {
        
        last_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 2;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 2;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 2;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 2;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private int ordinal_ ;
      /**
       * <code>int32 ordinal = 3;</code>
       * @return The ordinal.
       */
      @java.lang.Override
      public int getOrdinal() {
        return ordinal_;
      }
      /**
       * <code>int32 ordinal = 3;</code>
       * @param value The ordinal to set.
       * @return This builder for chaining.
       */
      public Builder setOrdinal(int value) {
        
        ordinal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ordinal = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrdinal() {
        
        ordinal_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PartialLogEntryMetadata)
    }

    // @@protoc_insertion_point(class_scope:PartialLogEntryMetadata)
    private static final Entry.PartialLogEntryMetadata DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Entry.PartialLogEntryMetadata();
    }

    public static Entry.PartialLogEntryMetadata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PartialLogEntryMetadata>
        PARSER = new com.google.protobuf.AbstractParser<PartialLogEntryMetadata>() {
      @java.lang.Override
      public PartialLogEntryMetadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PartialLogEntryMetadata(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PartialLogEntryMetadata> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PartialLogEntryMetadata> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Entry.PartialLogEntryMetadata getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LogEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PartialLogEntryMetadata_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PartialLogEntryMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013entry.proto\"\204\001\n\010LogEntry\022\016\n\006source\030\001 \001" +
      "(\t\022\021\n\ttime_nano\030\002 \001(\003\022\014\n\004line\030\003 \001(\014\022\017\n\007p" +
      "artial\030\004 \001(\010\0226\n\024partial_log_metadata\030\005 \001" +
      "(\0132\030.PartialLogEntryMetadata\"D\n\027PartialL" +
      "ogEntryMetadata\022\014\n\004last\030\001 \001(\010\022\n\n\002id\030\002 \001(" +
      "\t\022\017\n\007ordinal\030\003 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_LogEntry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LogEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LogEntry_descriptor,
        new java.lang.String[] { "Source", "TimeNano", "Line", "Partial", "PartialLogMetadata", });
    internal_static_PartialLogEntryMetadata_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PartialLogEntryMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PartialLogEntryMetadata_descriptor,
        new java.lang.String[] { "Last", "Id", "Ordinal", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
