version: "3.8"

services:
    postgresdb:
        image: postgres
        restart: always
        container_name: "Postgres"
        ports:
            - "5432:5432"
        volumes:
            - "postgres_data:/var/lib/postgresql/data"
        networks:
            - "overnet"
        environment:
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "password"
            POSTGRES_DB: "minecraft_logs"

volumes:
    postgres_data:

networks:
    overnet:
        external: true