name: DockerMC CI Pipeline

on:
  push:
    branches: [ "master" ]


jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      # Setup and compile the artifact
      - name: "Clone Code"
        uses: actions/checkout@v2
      - name: "Setup JDK 8"
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: "Install Commons"
        run: "mvn install -f Commons/pom.xml --quiet"
      - name: "Test"
        run: "ls ~/.m2/repository/de/derteufelqwe/Commons"
      - name: "Compile Log Driver"
        run: "mvn package -f DockerLogDriver/pom.xml --quiet"

      # Setup and push to docker
      - name: "Setup QEMU"
        uses: docker/setup-qemu-action@v1
      - name: "Setup docker Buildx"
        uses: docker/setup-buildx-action@v1
      - name: "Login to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Create the base image of the driver
      - name: "Create driver image"
        run: "cd DockerLogDriver && sh buildImage.sh"
